meveo/meveo-admin/web/src/main/java/org/meveo/admin/action/admin/UserRoleBean.java
/*
 * (C) Copyright 2015-2016 Opencell SAS (http://opencellsoft.com/) and contributors.
 * (C) Copyright 2009-2014 Manaty SARL (http://manaty.net/) and contributors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
 * This program is not suitable for any direct or indirect application in MILITARY industry
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.meveo.admin.action.admin;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.inject.Inject;
import javax.inject.Named;

import org.meveo.admin.action.BaseBean;
import org.meveo.admin.exception.BusinessException;
import org.meveo.admin.web.interceptor.ActionMethod;
import org.meveo.model.security.Permission;
import org.meveo.model.security.Role;
import org.meveo.service.admin.impl.PermissionService;
import org.meveo.service.admin.impl.RoleService;
import org.meveo.service.base.PersistenceService;
import org.meveo.service.base.local.IPersistenceService;
import org.omnifaces.cdi.ViewScoped;
import org.primefaces.model.DualListModel;

/**
 * Standard backing bean for {@link Role} (extends {@link BaseBean} that provides almost all common methods to handle entities filtering/sorting in datatable, their create, edit,
 * view, delete operations). It works with Manaty custom JSF components.
 */
@Named
@ViewScoped
public class UserRoleBean extends BaseBean<Role> {

    private static final long serialVersionUID = 1L;

    /** Injected @{link Role} service. Extends {@link PersistenceService}. */
    @Inject
    private RoleService userRoleService;

    @Inject
    private PermissionService permissionService;

    private DualListModel<Permission> permissionsDM;

    private DualListModel<Role> rolesDM;

    /**
     * Constructor. Invokes super constructor and provides class type of this bean for {@link BaseBean}.
     */
    public UserRoleBean() {
        super(Role.class);
    }

    public DualListModel<Permission> getPermissionListModel() {
        if (permissionsDM == null) {
            List<Permission> perksSource = permissionService.list();
            List<Permission> perksTarget = new ArrayList<Permission>();
            if (getEntity().getPermissions() != null) {
                perksTarget.addAll(getEntity().getPermissions());
            }
            perksSource.removeAll(perksTarget);
            permissionsDM = new DualListModel<Permission>(perksSource, perksTarget);
        }
        return permissionsDM;
    }

    public void setPermissionListModel(DualListModel<Permission> perks) {
        this.permissionsDM = perks;
    }

    public DualListModel<Role> getRoleListModel() {
        if (rolesDM == null) {
            List<Role> perksSource = userRoleService.list();
            perksSource.remove(getEntity());
            List<Role> perksTarget = new ArrayList<Role>();
            if (getEntity().getRoles() != null) {
                perksTarget.addAll(getEntity().getRoles());
            }
            perksSource.removeAll(perksTarget);
            rolesDM = new DualListModel<Role>(perksSource, perksTarget);
        }
        return rolesDM;
    }

    public void setRoleListModel(DualListModel<Role> perks) {
        this.rolesDM = perks;
    }

    /**
     * On provider change reset role and permission picklists
     */
    public void onProviderChange() {
        rolesDM = null;
    }

    @Override
    @ActionMethod
    public String saveOrUpdate(boolean killConversation) throws BusinessException {

        // Update permissions
        getEntity().getPermissions().clear();
        getEntity().getPermissions().addAll(permissionService.refreshOrRetrieve(permissionsDM.getTarget()));

        // Update roles
        getEntity().getRoles().clear();
        getEntity().getRoles().addAll(userRoleService.refreshOrRetrieve(rolesDM.getTarget()));

        return super.saveOrUpdate(killConversation);
    }

    /**
     * @see org.meveo.admin.action.BaseBean#getPersistenceService()
     */
    @Override
    protected IPersistenceService<Role> getPersistenceService() {
        return userRoleService;
    }

    /**
     * Add additional criteria for searching by provider
     */
    @Override
    protected Map<String, Object> supplementSearchCriteria(Map<String, Object> searchCriteria) {

        // Do not user a check against user.provider as it contains only one value, while user can be linked to various providers
        // boolean isSuperAdmin = identity.hasPermission("superAdmin", "superAdminManagement");
        //boolean isSuperAdmin = currentUser.hasPermission("superAdmin", "superAdminManagement");
//        if (isSuperAdmin) {
//            searchCriteria.put(PersistenceService.SEARCH_SKIP_PROVIDER_CONSTRAINT, true);
//        }

        return searchCriteria;
    }
}

meveo/meveo-admin/web/src/main/webapp/pages/admin/userRoles/userRoleDetail.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:s="http://jboss.com/products/seam/taglib" xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:hftl="http://hftl.org" xmlns:p="http://primefaces.org/ui"
    xmlns:hf="http://java.sun.com/jsf/composite/tags" template="/layout/template.xhtml">

    <ui:define name="metadata">
        <f:metadata>
            <f:viewParam name="objectId" value="#{userRoleBean.objectId}" />
        </f:metadata>
    </ui:define>
    
    <ui:define name="navigation">
        <ui:include src="/layout/navigation.xhtml" />
    </ui:define>

    <ui:define name="body">
        <p:panel>
            <h:form id="crumbmenuForm">
                <p:breadCrumb homeDisplay="text" id="crumbmenu">
                    <p:menuitem value="#{messages['menu.admin']}" disabled="true" />
                    <p:menuitem outcome="roles" value="#{messages['menu.userRoles']}" />
                </p:breadCrumb>
            </h:form>
        </p:panel>
        <hftl:formPanel label="#{messages['role.userRolePanel']}" backingBean="#{userRoleBean}">
            <hftl:formField label="#{messages['role.name']}" field="name" required="true" />
            <hftl:formField label="#{messages['businessEntity.description']}" field="description" size="50" maxlength="50" />
            <h:panelGroup id="providerDependentInfo">
                <hftl:formField label="#{messages['role.roles']}" field="roles" listType="pickUpList" dualListModel="#{userRoleBean.roleListModel}" valueLabelField="name"
                    styleClass="clearLeft" />
                <hftl:formField label="#{messages['role.permission']}" field="permissions" listType="pickUpList" dualListModel="#{userRoleBean.permissionListModel}"
                    valueLabelField="name" />
            </h:panelGroup>
        </hftl:formPanel>
    </ui:define>
</ui:composition>

meveo/meveo-admin/web/src/main/webapp/pages/admin/userRoles/userRoles.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:hftl="http://hftl.org" template="/layout/template.xhtml">

    <ui:define name="metadata">
        <f:metadata>
            <f:event type="preRenderView" listener="#{userRoleListBean.preRenderView}" />
        </f:metadata>
    </ui:define>

    <ui:define name="navigation">
        <ui:include src="/layout/navigation.xhtml" />
    </ui:define>

    <ui:define name="body">

        <hftl:searchPanel label="#{messages['role.search']}" backingBean="#{userRoleListBean}">
            <hftl:searchField label="#{messages['role.name']}" field="name" />
            <hftl:searchField label="#{messages['role.description']}" field="description" />
        </hftl:searchPanel>

        <hftl:dataList label="#{messages['role.title']}" backingBean="#{userRoleListBean}" sortBy="name">
            <hftl:column label="#{messages['role.name']}" field="name" entityView="roleDetail" valueIdField="id"/>
            <hftl:column label="#{messages['role.description']}" field="description" />
            <hftl:column label="#{messages['role.permissions']}" field="permissions" valueLabelField="name" isList="true" /> 

            <hftl:actionsColumn permission="#{identity.hasPermission('administration','administrationManagement')}" />

        </hftl:dataList>

    </ui:define>

</ui:composition>