meveo/meveo-admin/web/src/main/java/org/meveo/admin/action/document/AccountEntityBean.java
package org.meveo.admin.action.document;
import java.sql.BatchUpdateException;

import javax.inject.Inject;
import javax.inject.Named;

import org.meveo.admin.action.BaseBean;
import org.meveo.model.admin.AccountEntity;
import org.meveo.service.base.PersistenceService;
import org.meveo.service.base.local.IPersistenceService;
import org.meveo.service.document.AccountEntityService;
import org.omnifaces.cdi.ViewScoped;

@Named
@ViewScoped
public class AccountEntityBean extends BaseBean<AccountEntity> {

    private static final long serialVersionUID = -2634473401390003093L;

    /**
     * Injected @{link Title} service. Extends {@link PersistenceService}.
     */
    @Inject
    private AccountEntityService accountEntityService;

    /**
     * Constructor. Invokes super constructor and provides class type of this bean for {@link BaseBean}.
     */
    public AccountEntityBean() {
        super(AccountEntity.class);
       
    }
    
    @Override
    public String getListViewName(){
    	return "accountEntities";
    }

    /**
     * @see org.meveo.admin.action.BaseBean#getPersistenceService()
     */
    @Override
    protected IPersistenceService<AccountEntity> getPersistenceService() {
        return (IPersistenceService<AccountEntity>) accountEntityService;
    }

    public void test() throws BatchUpdateException {
        throw new BatchUpdateException();
    }

}

meveo/meveo-admin/web/src/main/java/org/meveo/admin/action/document/AccountEntityListBean.java
package org.meveo.admin.action.document;

import javax.enterprise.context.ConversationScoped;
import javax.inject.Named;

@Named
@ConversationScoped
public class AccountEntityListBean extends AccountEntityBean {

    private static final long serialVersionUID = 5761299788298195322L;
}

meveo/meveo-admin/web/src/main/java/org/meveo/admin/action/document/AccountingFirmBean.java
/*
 * (C) Copyright 2015-2016 Opencell SAS (http://opencellsoft.com/) and contributors.
 * (C) Copyright 2009-2014 Manaty SARL (http://manaty.net/) and contributors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
 * This program is not suitable for any direct or indirect application in MILITARY industry
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.meveo.admin.action.document;

import java.util.HashMap;

import javax.inject.Inject;
import javax.inject.Named;

import org.meveo.admin.action.BaseBean;
import org.meveo.admin.exception.BusinessException;
import org.meveo.documents.AccountingFirm;
import org.meveo.model.admin.AccountType.AccountTypeEnum;
import org.meveo.service.account.AccountTypeService;
import org.meveo.service.base.local.IPersistenceService;
import org.meveo.service.document.AccountingFirmService;
import org.omnifaces.cdi.ViewScoped;
import org.primefaces.model.LazyDataModel;

@Named
@ViewScoped
public class AccountingFirmBean extends BaseBean<AccountingFirm> {

    private static final long serialVersionUID = -2634473401398553083L;

  
    @Inject
    private AccountingFirmService accountingFirmService;
    
    @Inject
    private AccountTypeService accountTypeService;

    /**
     * Constructor. Invokes super constructor and provides class type of this bean for {@link BaseBean}.
     */
    
    public AccountingFirmBean() {
   	 super(AccountingFirm.class);
   }
  
    
    @Override
	protected IPersistenceService<AccountingFirm> getPersistenceService() {
		return (IPersistenceService<AccountingFirm>) accountingFirmService;
	}
    
    


    @Override
    public String saveOrUpdate(boolean killConversation) throws BusinessException {
    	entity.setAccountType(accountTypeService.getAccountType(AccountTypeEnum.expertComptable)); 
    	return super.saveOrUpdate(killConversation);
    }
    
    

    public LazyDataModel<AccountingFirm> getAccountingFirms(){
    	if (filters == null){
    		filters = new HashMap<>();
    	} 
    	filters.put("accountType.accountTypeEnum",AccountTypeEnum.expertComptable);
    	return getLazyDataModel();
    }
	
	
  

}

meveo/meveo-admin/web/src/main/java/org/meveo/admin/action/document/DocumentsAction.java
package org.meveo.admin.action.document;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.enterprise.inject.Produces;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.seam.international.status.Messages;
import org.jboss.solder.logging.Logger;
import org.meveo.admin.util.pagination.PaginationDataModel;
import org.meveo.services.repository.DocumentService;
import org.meveo.util.view.PaginationConfiguration;

import com.lowagie.text.Document;

@ConversationScoped
@Named
public class DocumentsAction  implements Serializable {


    /**
     * 
     */
    private static final long serialVersionUID = 5714791260420135724L;

    @Inject
    private Logger log;
    
    @Inject
    DocumentService documentService;
    
    @Inject
    private Messages messages;

    @Inject
    private Conversation conversation;

    String accountCode;
    String filename;
    
    private int pageSize = 20;

    private PaginationDataModel<Document> documentsDataModel;
    
    /***********************************************************************************/
    /* JSF INTERACTION */
    /***********************************************************************************/

    
    /**
     * ACTIONS
     */
    
    @Produces
    @ConversationScoped
    @Named("documentsDataModel")
    public PaginationDataModel<Document> find() {
        // if(currentUser.getBusinessAccount() instanceof CustomerAccount){
        // this.accountCode = ((CustomerAccount)currentUser.getBusinessAccount()).getRef1();
        // }

        if (documentsDataModel == null) {
            documentsDataModel = new DocumentsDataModel();
        }

        documentsDataModel.forceRefresh();

        return documentsDataModel;
    }

    public String getAccountCode() {
        return accountCode;
    }

    public void setAccountCode(String accountCode) {
        // if(currentUser.getBusinessAccount() instanceof CustomerAccount){
        // this.accountCode = ((CustomerAccount)currentUser.getBusinessAccount()).getRef1();
        // }

        this.accountCode = accountCode;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    public void refresh() {
        documentsDataModel = new DocumentsDataModel();
        find();
    }

    
    /***********************************************************************************/
    /* DATATABLE MODEL */
    /***********************************************************************************/
    class DocumentsDataModel extends PaginationDataModel<Document> {

        private static final long serialVersionUID = 1L;

//        @Override
//        protected int countRecords(PaginationConfiguration paginatingData) {
//            int documentCount = (int) documentService.count(accountCode,filename);
//            return documentCount;
//        }
//
//        @Override
//        protected List<Document> loadData(PaginationConfiguration configuration) {
//            return documentService.find(accountCode,filename,configuration);
//        }
    }
}
		

meveo/meveo-admin/web/src/main/java/org/meveo/admin/action/document/DossierBean.java
/*
 * (C) Copyright 2015-2016 Opencell SAS (http://opencellsoft.com/) and contributors.
 * (C) Copyright 2009-2014 Manaty SARL (http://manaty.net/) and contributors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
 * This program is not suitable for any direct or indirect application in MILITARY industry
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.meveo.admin.action.document;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.inject.Inject;
import javax.inject.Named;

import org.meveo.admin.action.BaseBean;
import org.meveo.admin.exception.BusinessException;
import org.meveo.documents.Dossier;
import org.meveo.model.admin.AccountType.AccountTypeEnum;
import org.meveo.model.admin.User;
import org.meveo.service.account.AccountTypeService;
import org.meveo.service.admin.impl.UserService;
import org.meveo.service.base.local.IPersistenceService;
import org.meveo.service.document.DossierService;
import org.omnifaces.cdi.ViewScoped;
import org.primefaces.model.LazyDataModel;

@Named
@ViewScoped
public class DossierBean extends BaseBean<Dossier> {

    private static final long serialVersionUID = -2634473401398553083L;

  
    @Inject
    private DossierService dossierService;
    
    @Inject
    private UserService userService;
    
    @Inject
    private AccountTypeService accountTypeService;

    /**
     * Constructor. Invokes super constructor and provides class type of this bean for {@link BaseBean}.
     */
    
    public DossierBean() {
   	 super(Dossier.class);
   }
  
    
    @Override
	protected IPersistenceService<Dossier> getPersistenceService() {
		return (IPersistenceService<Dossier>) dossierService;
	}

    
	@Override
	public String saveOrUpdate(boolean killConversation) throws BusinessException {
       // entity.setAccountType(accountTypeService.getAccountType(AccountTypeEnum.dossier)); 
        return super.saveOrUpdate(killConversation);
    }
	
	 public List<User> getResponsiblesEc() {
	    	List<User> UserList = new ArrayList<User>(); 
	    	List<User> userMangers = new ArrayList<User>(); 
	    	UserList=userService.list();
	    	if(UserList.size()>0){
	    	for(User user:UserList){
	    		if(user.hasRole("serviceManager")){
	    			userMangers.add(user);
	    		}
	    	}}
	        return userMangers;
	    }
	 
	 
	 public List<User> getAssociates() {
	    	List<User> users = new ArrayList<User>();  
	    	List<User> userAssociats = new ArrayList<User>(); 
	    	users=userService.list();
	    	if(users.size()>0){
	    	for(User user:users){
	    		if(user.hasRole("associate")){
	    			userAssociats.add(user);
	    		}
	    	}}
	        return userAssociats;
	    }
	 
	 public List<User> getResponsibles() {
	    	List<User> allUsers= new ArrayList<User>();
	    	List<User> userResponsibles = new ArrayList<User>(); 
	    	allUsers=userService.list();
	    	if(allUsers.size()>0){
	    	for(User user:allUsers){
	    		if(user.hasRole("associate") || user.hasRole("accountant") ){
	    			userResponsibles.add(user);
	    		}
	    	}}
	        return userResponsibles;
	    }
	   public LazyDataModel<Dossier> getDossiers(){
			if (filters == null){
				filters = new HashMap<>();
			} 
			filters.put("accountType.accountTypeEnum",AccountTypeEnum.dossier);
			return getLazyDataModel();
		}
	
	
  

}

meveo/meveo-admin/web/src/main/java/org/meveo/admin/action/document/DossierListBean.java
/*
 * (C) Copyright 2015-2016 Opencell SAS (http://opencellsoft.com/) and contributors.
 * (C) Copyright 2009-2014 Manaty SARL (http://manaty.net/) and contributors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
 * This program is not suitable for any direct or indirect application in MILITARY industry
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.meveo.admin.action.document;

import javax.enterprise.context.ConversationScoped;
import javax.inject.Named;

@Named
@ConversationScoped
public class DossierListBean extends DossierBean {

	private static final long serialVersionUID = 1L;

	

}

meveo/meveo-admin/web/src/main/webapp/pages/documents/accountingFirm/accountEntities.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:s="http://jboss.com/products/seam/taglib"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html" xmlns:hftl="http://hftl.org"
	xmlns:hf="http://java.sun.com/jsf/composite/tags" xmlns:p="http://primefaces.org/ui"
	template="/layout/template.xhtml">

	<ui:define name="metadata">
		<f:metadata>
			<f:event type="preRenderView" listener="#{accountEntityListBean.preRenderView}" />
		</f:metadata>
	</ui:define>

	<ui:define name="navigation">
		<ui:include src="/layout/navigation.xhtml" />
	</ui:define>

	<ui:define name="body">

		<hftl:searchPanel backingBean="#{accountEntityListBean}"
			label="#{messages['accountingFirm.search']}">
			<hftl:searchField label="#{messages['businessEntity.code']}" field="code" />
			<hftl:searchField label="#{messages['accountingFirm.name']}" field="name" />
		</hftl:searchPanel>

		<hftl:dataList label="#{messages['accountingFirm.accountingFirmPanel']}"
			backingBean="#{accountEntityListBean}" sortBy="name">
			<hftl:column label="#{messages['businessEntity.code']}" field="code"/>
			<hftl:column label="#{messages['accountingFirm.name']}" field="name" entityView="accountEntityDetail" valueIdField="id"/>
			<hftl:column label="#{messages['address.zipCode']}" field="contacts.postalCode"/>
			<hftl:column label="#{messages['address.city']}" field="contacts.city"/>
			<hftl:column label="#{messages['accountingFirm.accountType']}" field="accountType.code" />
			<hftl:column label="#{messages['businessAccount.disabled']}" field="disabled" />             
			<hftl:actionsColumn/>
		</hftl:dataList>
  
    </ui:define>

</ui:composition>

meveo/meveo-admin/web/src/main/webapp/pages/documents/accountingFirm/accountEntityDetail.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:s="http://jboss.com/products/seam/taglib" xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:hftl="http://hftl.org" xmlns:hf="http://java.sun.com/jsf/composite/tags"
    xmlns:c="http://java.sun.com/jstl/core" xmlns:p="http://primefaces.org/ui" template="/layout/template.xhtml">

    <ui:define name="navigation">
        <ui:include src="/layout/navigation.xhtml" />
    </ui:define>

    <ui:define name="body">

        <p:panel>
            <h:form id="crumbmenuForm">
                <p:breadCrumb homeDisplay="text" id="crumbmenu">
                    <p:menuitem value="#{messages['menu.accountingFirms']}" disabled="true" />
                    <p:menuitem outcome="accountEntities" value="#{messages['menu.accountingFirms']}" />
                </p:breadCrumb>
            </h:form>
        </p:panel>
        <hftl:formPanel label="#{messages['accountingFirm.accountingFirmPanel']}" backingBean="#{accountEntityBean}">
        <p:panelGrid columns="2" style="border:none important!">
	        <hftl:formField label="#{messages['businessEntity.code']}" field="code" required="true" validateUnique="true" />
			<hftl:formField label="#{messages['accountingFirm.name']}" field="name" required="true"/>
			<hftl:formField label="#{messages['address.address1']}" field ="contacts" childField="address1" />
			<hftl:formField label="#{messages['address.address2']}" field ="contacts" childField="address2" />
			<hftl:formField label="#{messages['address.address3']}" field ="contacts" childField="address3" />
			<hftl:formField label="#{messages['address.zipCode']}" field ="contacts" childField="postalCode" />
			<hftl:formField label="#{messages['address.city']}" field ="contacts" childField="city" />
			<hftl:formField label="#{messages['address.phone']}" field ="contacts" childField="phone" />
			  </p:panelGrid>
        </hftl:formPanel>

    </ui:define>

</ui:composition>